version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./model:/app/model

  frontend:
    build: ./frontend-ui
    ports:
      - "3000:3000"
  depends_on:
      - backend